services:
    akeneo.pim.enrichment.factory.read.value.boolean:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\BooleanValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.date:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\DateValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.file:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\FileValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.image:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\ImageValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.identifier:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\IdentifierValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.metric:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\MetricValueFactory
        arguments:
            $metricFactory: '@pim_catalog.factory.metric'
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.number:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\NumberValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.options:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\OptionsValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.option:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\OptionValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.price_collection:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\PriceCollectionValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.reference_data_collection:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\ReferenceDataCollectionValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.reference_data:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\ReferenceDataValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.textarea:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\TextAreaValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value.text:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\Value\TextValueFactory
        tags: ['akeneo.pim.enrichment.factory.read.product_value']

    akeneo.pim.enrichment.factory.read.value:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\ValueFactory
        arguments:
            $valueFactories: !tagged akeneo.pim.enrichment.factory.read.product_value

    akeneo.pim.enrichment.factory.read.value_collection:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\ValueCollectionFactory
        arguments:
            $valueFactory: '@akeneo.pim.enrichment.factory.read.value'
            $getAttributeByCodes: '@akeneo.pim.structure.query.get_attributes'
            $chainedNonExistentValuesFilter: '@akeneo.pim.enrichment.factory.non_existent_values_filter.chained'
            $emptyValuesCleaner: '@akeneo.pim.enrichment.factory.empty_values_cleaner'
            $transformRawValuesCollections: '@akeneo.pim.enrichment.factory.transform_raw_values_collections'

    akeneo.pim.enrichment.factory.read.write_value_collection:
        class: Akeneo\Pim\Enrichment\Component\Product\Factory\Read\WriteValueCollectionFactory
        arguments:
            $valueFactory: '@akeneo.pim.enrichment.factory.read.value'
            $getAttributeByCodes: '@akeneo.pim.structure.query.get_attributes'
            $chainedNonExistentValuesFilter: '@akeneo.pim.enrichment.factory.non_existent_values_filter.chained'
            $emptyValuesCleaner: '@akeneo.pim.enrichment.factory.empty_values_cleaner'
            $transformRawValuesCollections: '@akeneo.pim.enrichment.factory.transform_raw_values_collections'
